/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c Device -p generated/org_freedesktop_networkmanager_device /home/kazushin/WorkSpace/Deepin/dde-qt-dbus-factory/xml/org.freedesktop.NetworkManager.Device.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <DBusExtendedAbstractInterface>
#include <QtDBus/QtDBus>


/*
 * Proxy class for interface org.freedesktop.NetworkManager.Device
 */
class __Device : public DBusExtendedAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.NetworkManager.Device"; }

public:
    explicit __Device(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~__Device();

    Q_PROPERTY(QString Interface READ interface NOTIFY InterfaceChanged)
    inline QString interface()
    { return qvariant_cast< QString >(internalPropGet("Interface", &m_Interface)); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
// begin property changed signals
    void InterfaceChanged(const QString & value) const;

// begin private slots
private Q_SLOTS:
    void onPropertyChanged(const QString &propName, const QVariant &value);

// begin private member vaiables
private:
    QString m_Interface;
};

namespace org {
  namespace freedesktop {
    namespace networkmanager {
      typedef ::__Device Device;
    }
  }
}
#endif
