/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c Wallpaper -p generated/com_deepin_dde_wallpaper /home/kirigaya/projects/Deepin/dde-qt-dbus-factory/xml/com.deepin.dde.Wallpaper.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "com_deepin_dde_wallpaper.h"

/*
 * Implementation of interface class __Wallpaper
 */

__Wallpaper::__Wallpaper(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusExtendedAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

__Wallpaper::~__Wallpaper()
{
}

